server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html/;
    index index.html;

    location = /supplierportal {
        try_files /supplierportal/index.html =404;
    }

    location /supplierportal/ {
        try_files $uri $uri/ /supplierportal/index.html;
    }

    location = /supplierportal/config.json {
        alias /usr/share/nginx/html/config.json;
    }

    location /api/public/supplierportal/ {
        try_files $uri $uri/ /supplierportal/index.html;
    }

    location = /api/public/supplierportal {
        try_files /supplierportal/index.html =404;
    }

    location = /api/public/supplierportal/config.json {
        alias /usr/share/nginx/html/config-public.json;
    }

    error_page 404 /404.html;
    error_page 500 502 503 504  /50x.html;
}
