server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html/;
    index index.html;

    location = /disclosureportal-supplierui {
        try_files /disclosureportal-supplierui/index.html =404;
    }

    location /disclosureportal-supplierui/ {
        try_files $uri $uri/ /disclosureportal-supplierui/index.html;
    }

    location = /disclosureportal-supplierui/config.json {
        alias /usr/share/nginx/html/config.json;
    }

    location /api/public/disclosureportal-supplierui/ {
        try_files $uri $uri/ /disclosureportal-supplierui/index.html;
    }

    location = /api/public/disclosureportal-supplierui {
        try_files /disclosureportal-supplierui/index.html =404;
    }

    location = /api/public/disclosureportal-supplierui/config.json {
        alias /usr/share/nginx/html/config-public.json;
    }

    error_page 404 /404.html;
    error_page 500 502 503 504  /50x.html;
}
